# Generated by Django 3.0.2 on 2020-02-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0003_auto_20200212_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location1',
        ),
    ]
