# Generated by Django 3.0.2 on 2020-02-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0004_delete_location1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='couponcode',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='transid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='trek',
            field=models.CharField(choices=[('1111', 12000), ('2222 ', 20000), ('22222 ', 'trek3 price 3r4562')], max_length=120),
        ),
    ]
