# Generated by Django 3.0.2 on 2020-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0005_auto_20200218_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
