# Generated by Django 3.0.2 on 2020-02-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0006_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='transid',
        ),
        migrations.AlterField(
            model_name='product',
            name='trek',
            field=models.CharField(choices=[('kedarkantha', 'kedarkantha'), ('2222 ', 20000), ('22222 ', 'trek3 price 3r4562')], max_length=120),
        ),
    ]
