# Generated by Django 3.0.2 on 2020-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0008_auto_20200220_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='idp',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
