# Generated by Django 3.0.2 on 2020-02-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0009_auto_20200220_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='idp',
        ),
        migrations.AddField(
            model_name='product',
            name='id_proof',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
