# Generated by Django 3.0.2 on 2020-02-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0010_auto_20200220_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='transid',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
