# Generated by Django 3.0.2 on 2020-02-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0011_auto_20200221_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upiname',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
