# Generated by Django 3.0.2 on 2020-02-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0012_product_upiname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upi',
            old_name='name',
            new_name='upiname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='transid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='upiname',
        ),
    ]
