# Generated by Django 3.0.2 on 2020-02-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0013_auto_20200221_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='upi',
            name='confirm',
            field=models.CharField(default='no', max_length=5),
            preserve_default=False,
        ),
    ]
