# Generated by Django 3.0.2 on 2020-02-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0015_auto_20200223_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upi',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='upi',
            name='name',
        ),
    ]
